[theme]
base = "light"
primaryColor = "#69c987"
backgroundColor = "#fbf8ef"
secondaryBackgroundColor = "#fffdf7"
textColor = "#263426"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
